---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-grafana
  labels:
    helm.sh/chart: grafana-0.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "9.4.7"
    app.kubernetes.io/managed-by: Helm
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-grafana
  labels:
    helm.sh/chart: grafana-0.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "9.4.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-grafana
  labels:
    helm.sh/chart: grafana-0.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "9.4.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: app
    spec:
      serviceAccountName: app-grafana
      securityContext:
        {}
      containers:
        - name: grafana
          securityContext:
            {}
          image: "docker.io/grafana/grafana:9.4.7"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-grafana
  labels:
    helm.sh/chart: grafana-0.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "9.4.7"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "grafana.172-16-1-9.nip.io"
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: app-grafana
                port:
                  number: 3000
---
# Source: grafana/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "app-grafana-test-connection"
  labels:
    helm.sh/chart: grafana-0.1.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "9.4.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['app-grafana:3000']
  restartPolicy: Never
